### ISSUE TITLE
CannotCreateExternalResource EOF error

### ISSUE THREAD

**Issue by lariskovski** [crossplane-contrib/provider-kafka#53]
### What happened?

After following the documentation I expected to be able to deploy a topic resource. Instead I keep getting the erros below on the kafka-provider's logs:

```
[ERROR] unable to request api versions; broker: seed 0, err: EOF
[provider-kafka] 2023-01-30T14:40:29.762ZDEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"Topic","name":"sample-topic","uid":"xxxx","apiVersion":"topic.kafka.crossplane.io/v1alpha1","resourceVersion":"1200071675"}, "reason": "CannotCreateExternalResource", "message": "EOF"}
```
`topic.yaml`
```
apiVersion: topic.kafka.crossplane.io/v1alpha1
kind: Topic
metadata:
  name: sample-topic
spec:
  forProvider:
    replicationFactor: 1
    partitions: 1
  providerConfigRef:
    name: kafka-stage-provider
```

### How can we reproduce it?

I followed the README steps, deployed the topic resource and looked for the provider logs

### What environment did it happen in?

Crossplane version:  helm.sh/chart: crossplane-1.7.0
Kubernetes distribution: GKE 1.21
Kafka: Confluent Cluster
