### ISSUE TITLE
Authenticate with AWS IAM Role

### ISSUE THREAD

**Issue by davimmt** [crossplane-contrib/provider-kafka#78]
### What problem are you facing?
Deploy the provider in a Crossplane inside AWS EKS and use AWS IRSA for authentication. However, I did not find docs to help me do it.

### How could Crossplane help solve your problem?
Provide documentation on how to authenticate with AWS IAM Role.

---

After trying various ways to authenticate using SALS/SCRAM with AWS Secrets Managers User/Password method, as indicated [here](https://github.com/crossplane-contrib/provider-kafka/blob/main/README.md?plain=1#L8-L22), and not getting it, I started reading the source code and found [this](https://github.com/crossplane-contrib/provider-kafka/blob/main/internal/clients/kafka/client.go#L59-L61).

So, the working credentials files is (brokers endpoints are generated by your AWS MSK Cluster):
```json
{
  "brokers": [
    "b-1.<cluster-name>.xxxxx.xx.kafka.<region>.amazonaws.com:9098",
    "b-2.<cluster-name>.xxxxx.xx.kafka.<region>.amazonaws.com:9098"
  ],
  "sasl": {
    "mechanism": "aws-msk-iam"
  },
  "tls": {
    "insecureSkipVerify": false
  }
}
```

And least privilege AWS IAM Policy for using this Crossplane provider to manage Topics:
```json
{
  "Action": [
    "kafka-cluster:Connect",
    "kafka-cluster:CreateTopic",
    "kafka-cluster:DeleteTopic",
    "kafka-cluster:DescribeTopic",
    "kafka-cluster:DescribeTopicDynamicConfiguration",
    "kafka-cluster:AlterTopic",
    "kafka-cluster:AlterTopicDynamicConfiguration"
  ],
  "Effect": "Allow",
  "Resource": [
    "arn:aws:kafka:<aws-region>:<aws-account-id>:cluster/<cluster-name>/<cluster-id>",
    "arn:aws:kafka:<aws-region>:<aws-account-id>:topic/<cluster-name>/<cluster-id>/<topic-name>"
  ]
}
```
Should a doc exist for this?

**Comment by quanlk2511** [comment]
Hi @davimmt ,  which version of provider-kafka & crossplane are you using?

Also, can you share your providerConfig?

I'm struggling to use aws-msk-iam with IRSA/ source InjectedIdentity

It keeps throwing out this error: "cannot get credentials: no extraction handler registered for source: InjectedIdentity", "CannotConnectToProvider"

Thanks,

**Comment by davimmt** [comment]
Hello, sorru for taking so long, Didn't see it til now, @quanlk2511.

Here's the snippet:
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kafka
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kafka:v0.5.0
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-creds
type: Opaque
data:
  credentials: xxx
  # {
  #   "brokers":[
  #     "b-1.xxx.xxx.c3.kafka.sa-east-1.amazonaws.com:9098",
  #     "b-2.xxx.xxx.c3.kafka.sa-east-1.amazonaws.com:9098"
  #   ],
  #   "sasl":{
  #     "mechanism":"aws-msk-iam"
  #   },
  #   "tls": {
  #     "insecureSkipVerify": false
  #   }
  # }
---
apiVersion: kafka.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    secretRef:
      key: credentials
      name: kafka-creds
    source: Secret
```
